Cover Sheet
========================================================


By including this statement, we, all the students listed in the table
below, declare that:

- We hold a copy of this assignment if the original is lost or damaged.

- We hereby certify that no part of this assignment has been copied from
  any other student's work or from any other source except where due
  acknowledgement is made in the assignment.

- No part of the assignment has been written for us by any other person
  except where collaboration has been authorised by the unit coordinator.

- We are aware that this work may be reproduced and submitted to plagiarism
  detection software programs for the purpose of detecting possible
  plagiarism; this software may retain a copy on its database for future
  plagiarism checking.

- We hereby certify that no part of this assignment or product has been
  submitted by any of us in another (previous or current) assessment, except
  where appropriately referenced, and with prior permission from the unit
  coordinator for this unit.

- We hereby certify that we have read and understand what the University
  considers to be academic misconduct, and that we are aware of the
  penalties that may be imposed for academic misconduct.

Name               | Student Number | Contribution (%)
-------------------|----------------|-----------------
                   |                |
                   |                |
                   |                |
                   |                |

<div style="page-break-before:always;"></div>


Group Project
========================================================

Explain the assignment.


Part One
--------------------------------------------------------

Describe the problem in part one.

Solve the problem using R.
```{r}
##read data from the csv file
csvData = read.csv("FlyingFoxMonitoring.csv", header = TRUE)

##remove all rows of data with NA
mydata = na.omit(csvData)

##the true sum of  flying foxes
truesum = mydata$BlackFlyingFox.Count+mydata$GreyHeadedFlyingFox.Count+mydata$LittleRedFlyingFox.Count

##compare true sums to the sum in the csv and remove
#if values are not equal
mydata=mydata[(mydata$TotalSpecies.Count==truesum),]

```

Interpret the solution of the problem.

